### ISSUE TITLE
Do you have plan to train the base/middle version of Mamba2?

### ISSUE THREAD

**Issue by EricLina** [SH-Yoon-01/unofficial-VisionMamba2-Vim2#1]
Hello, thanks for your advanced work.
Do you have plan to train the base/middle version of Mamba2?🧐
I noticed that mamba2-tiny is worse than mambaout-tiny, would you still believe mamba?😂

**Comment by SH-Yoon-01** [comment]
Thank you for your fantastic work.

As of now, there are no immediate plans for the 'basic/middle version of VisionMamba2.' MambaOut has demonstrated superior performance to Vision Mamba in image classification tasks using supervised learning methods. However, the point that MambaOut aims to convey is that the 'causal inference' structure of Mamba leads to a performance decline when applied to certain vision tasks. Therefore, I still believe that Mamba has potential in the field of vision tasks, and I plan to explore ways to overcome the aforementioned limitations in the future.

**Comment by EricLina** [comment]
thanks.
